services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: networkmanager
      POSTGRES_USER: networkmanager
      POSTGRES_PASSWORD: thepassword
    ports:
      - "5432:5432"
